import {StyleSheet} from 'react-native';
import {colors} from '../../config';
export const styles = StyleSheet.create({
  container: {
    display: 'flex',
    flex: 1,
    margin: 15,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 30,
    paddingLeft: 10,
    paddingRight: 10,
  },
  basketWrapper: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    padding: 10,
    borderRadius: 15,
  },
  heading: {
    fontFamily: 'Cera Pro',
    fontWeight: 'bold',
    fontSize: 25,
    lineHeight: 30,
    color: colors.heading,
  },
  icon1: {
    width: 14,
    height: 14,
  },
  smallTitle: {
    color: 'white',
    fontSize: 14,
    marginLeft: 10,
  },
  footerWrapper: {
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  footerMenuItemWrapper: {
    flexDirection: 'row',
    backgroundColor: colors.gray01,
    padding: 10,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 20,
  },
  label: {
    color: colors.secondary,
    fontSize: 14,
    marginLeft: 10,
    fontFamily: 'Cera Pro',
  },
  label2: {
    color: colors.heading,
    fontFamily: 'Cera Pro',
    marginTop: 10,
    fontWeight: '500',
  },
  subTitleWrapper: {
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 5,
  },
  subTitle: {
    color: colors.gray02,
    fontSize: 12,
    fontFamily: 'Cera Pro',
  },
  searchBoxWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 25,
    backgroundColor: colors.gray01,
    padding: 15,
    borderRadius: 15,
  },
  categoryCard: {
    width: 70,
    height: 70,
    backgroundColor: colors.gray01,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
  },
  categoryItem: {
    marginRight: 25,
    alignItems: 'center',
  },
  categoryCardActive: {
    width: 70,
    height: 70,
    backgroundColor: colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 15,
  },
  categoryWrapper: {
    marginTop: 15,
  },
  subHeadingWrapper: {
    marginTop: 25,
    marginBottom: 15,
  },
  subHeading: {
    color: colors.heading,
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Cera Pro',
  },
  foodListingWrapper: {
    display: 'flex',
  },
  foodItemWrapper: {
    backgroundColor: colors.gray01,
    padding: 5,
    borderRadius: 10,
    marginBottom: 15,
  },
  foodImage: {
    width: '100%',
    borderRadius: 10,
  },
  foodItemTitle: {
    color: colors.heading,
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Cera Pro',
    padding: 10,
  },
  foodItemSpecs: {
    color: colors.gray02,
    fontSize: 16,
    fontWeight: '500',
    fontFamily: 'Cera Pro',
    paddingLeft: 10,
  },
  percentageWrapper: {
    flexDirection: 'row',
    padding: 10,
  },
  percentageText: {
    marginLeft: 10,
    color: colors.secondary,
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Cera Pro',
  },
  distance: {
    position: 'absolute',
    top: '40%',
    left: '8%',
    backgroundColor: colors.gray01,
    opacity: 0.6,
    padding: 10,
    borderRadius: 5,
  },
  distanceText: {
    color: colors.heading,
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'Cera Pro',
    paddingLeft: 10,
  },
});
